# https://v0-3-branch.zmk.dev/docs/features/lighting#rgb-underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n

CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=0
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=0
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=25
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1

# https://v0-3-branch.zmk.dev/docs/features/displays
CONFIG_ZMK_DISPLAY=y

# Power Management Configuration
# https://v0-3-branch.zmk.dev/docs/config/power#kconfig
CONFIG_ZMK_PM_SOFT_OFF=y

